OneSignal/OneSignal-XCFramework

Package.swift
This release includes the following fixes:
- Location track fix
- Firing subscription observer on every launch
- Removing identifierForVendor from register user
- Content Available notifications firing opened handler when received in foreground
=> Release 3.1.1

Package.swift
https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.2.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/8)
=> Release 3.2.2

Package.swift
IAM Tag Substitution 
External user already set fixes 
Ability to disable 'OneSignal load'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/11)
=> updating package for 3.3.0 release

Package.swift
release 3.4.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/12)
=> release 3.4.0

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/13)
=> release 3.4.1 

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/14)
=> release 3.4.2

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/16)
=> release 3.4.4

Package.swift
notification image fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/18)
=> release 3.5.2

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/19)
=> Release 3.5.3

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/20)
=> Release 3.6.0

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/21)
=> release 3.6.1

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/23)
=> release 3.7.0

Package.swift
iOS 15 feature release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/24)
=> release 3.8.0

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/25)
=> release 3.8.1

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/28)
=> release 3.9.0

Package.swift
fixing XCFramework architectures
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/30)
=> 3.9.1 release

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/31)
=> release 3.10.0

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/32)
=> release 3.10.1

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/33)
=> Release 3.10.2

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/35)
=> Release 3.10.3

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/39)
=> release 3.11.1

Package.swift
Updating Package.swift with the latest checksums
=> Release 3.11.2

Package.swift
**🚧 Alpha release. It is not recommended to use in production. 🚧**
**🚀 Features**
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1189
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1210
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1211
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/54)
=> Release 5.0.0-alpha-02

Package.swift
**🚧 Beta release. 🚧**
*************
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1229
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/56)
=> Release 5.0.0-beta-02

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/58)
=> Release 3.12.4

Package.swift
🚀 Features
- Enable push notifications for iOS simulators (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1244)
🐛 Bug Fixes
- Fix Crash for In App Message clicks with no id (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1248)
- Fix tracking influenced opens in firebase (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1241)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/59)
=> Updating package.swift for release 3.12.5

Package.swift
🐛 Bug Fixes
- Fix Swift Package Manager Validation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/67)
=> Update package.swift for 5.0.1 release

Package.swift
- Fix rare scenario where login requests are stuck and prevent the SDK from making updates (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1398)
**🎉 New Features**
- This release is also signed by the OneSignal certificate
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/82)
=> Release 5.1.4

Package.swift
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1390
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1395
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1396
------
This release was made with GitHub Action CD.
Tested with SPM successfully and able to archive app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/85)
=> Release 5.1.5

Package.swift
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1418
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1412
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1411
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1417
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1413
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/86)
=> Release 5.1.6

Package.swift
🎉 Identity Verification Support
--------
This beta release introduces Identity Verification support for the iOS user model SDK.
To get started with using Identity Verification, please contact support@onesignal.com to enable this feature for your app. Please see documentation on [Identity Verification](https://documentation.onesignal.com/docs/identity-verification).
We appreciate your experience and feedback using this beta version!
It is recommended to test this beta version with a new iOS-only app, as Identity Verification is not yet supported on the OneSignal Android and Web SDKs. Enabling Identity Verification in the dashboard will affect all existing app installations using the OneSignal user model SDKs. Please test thoroughly prior to production use, and reach out with any questions, …
=> Release 5.3.0-beta-01

Package.swift
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1493
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1494
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/101)
=> Release 3.12.10

Package.swift
- For our server only: Update a header value when the SDK fetches in-app messages https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1509
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/104)
=> Release 5.2.7

Package.swift
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1541
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1542
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/112)
=> Release 5.2.10

Package.swift
- Fix crashes in the user module (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1554)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/116)
=> Release 5.2.11

Package.swift
🐛 Bug Fixes
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1554
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1559
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/119)
=> Release 5.2.12

Package.swift
- Rebased to 5.2.14 for more bug fixes and stability improvement.
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/122)
=> Release 5.3.0-beta-02
