- Package.swift
- A new plist option `OneSignal_suppress_launch_urls` can be added to prevent OneSignal from opening launch URLs so that they can be handled by applications separately
- The OneSignal XCFramework will now build for both intel and Arm simulators on Apple Silicon macs
- OneSignal will now properly forward non-OneSignal notifications to Firebase
> Release 3.2.0

- Package.swift
Fixes suppress launch URL boolean being flipped
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/6)
> release 3.2.1

- Package.swift
Release 3.2.3 corresponding to [iOS SDK release 3.2.3](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.2.3)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/9)
> release 3.2.3

- Package.swift
corresponds to native sdk release https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.5.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/17)
> release 3.5.1

- Package.swift
This Package.swift should be identical to the OneSignal-iOS-SDK Package.swift apart from the package name. We will no longer need to run update_swift_package.sh instead we can just copy the OneSignal-iOS-SDK Package.swift here and change the package name.
I don't think we will want to sunset this repository since it allows customers to pull in our SDK without cloning our entire iOS SDK repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/34)
> Release 3.11.0-beta-01

- Package.swift
This repo no longer needs to run any build scripts we simply copy over the OneSignal-iOS-SDK package.swift and change the package name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/36)
> Updating package.swift for release 3.11.0

- Package.swift
* PR https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1132 Removed 32 bit architectures since they are not supported in Xcode 14, but this causes us to drop support for iOS 9 and 10. This release adds back the 32 bit architectures while still allowing us to develop in Xcode 14. #1134 
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1134
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/43)
> Release 3.11.4

- Package.swift
The last release PR (#43) had the wrong binaries and had to rebuild them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/44)
> Fixed checksums to match new bins for 3.11.4

- Package.swift
None
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/46)
> Release 3.11.5

- Package.swift
Added two public methods
* enterLiveActivity
* exitLiveActivity
These public methods make API calls and associate an `activityId` with a temporary push token on the OneSignal server
Users can now start a demo Live Activity from the example project.
Scroll down on the main screen and click "Start Live Activity"
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1150
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1152
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/47)
> Release 3.12.0

- Package.swift
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1155
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/49)
> Release 3.12.1

- Package.swift
Since `activity_id` is customer generated and shows up in the path to enter or exit a live activity it must be encoded.
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1159
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/50)
> Release 3.12.2

- Package.swift
app_id must be included with each request. In order to reduce load on the server we fail requests early on the client that we know will fail on the server. Currently the check in OneSignalRequest looks for app_id in the body as a param. However there is another valid way to send the app_id that is after "/apps" in the path".
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1163
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1162
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1161
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/51)
> Release 3.12.3

- Package.swift
In this major version alpha release for the OneSignal SDK, we are making a significant shift from a device-centered model to a user-centered model. A user-centered model allows for more powerful omni-channel integrations within the OneSignal platform.
Find our [migration guide here ](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/major_release_5.0.0/MIGRATION_GUIDE.md
)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-xcframework/53)
> Release 5.0.0 alpha 01

- Package.swift
**🚧 Beta release. 🚧**
*************
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/55)
> Release 5.0.0-beta-01

- Package.swift
🚧 Beta release. 🚧
Notification, In App Message, and Push Subscription events have been renamed. The migration guide has been updated to reflect the changes.
- [5.0.0] API Updates #1255
- [5.0.0] Notification Permission Observer - API update #1256
- [5.0.0] IAM Lifecycle Listener - API update #1257
- [5.0.0] Notification Foreground Listener - API update #1258
- [5.0.0] Push Subscription Observer - API …
> Release 5.0.0 beta 03

- Package.swift
🚧 Beta release. 🚧
Various Small Fixes
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1265
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1266
**Full Changelog**: https://github.com/OneSignal/OneSignal-iOS-SDK/compare/5.0.0-beta-03...5.0.0-beta-04
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Release 5.0.0-beta-04

- Package.swift
🚧 Beta release. 🚧
**Modularization of InAppMessages and Location**
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1273
**Removal of launch urls in app**
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1275
**Various Small Fixes**
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1279
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1278
- - -
This change is [<img …
> Release 5.0.0-beta-05

- Package.swift
🚧 Beta release. 🚧
**Fix a podspec build issue**
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1281
**Full Changelog**: https://github.com/OneSignal/OneSignal-iOS-SDK/compare/5.0.0-beta-05...5.0.0-beta-06
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/63)
> Release 5.0.0-beta-06

- Package.swift
🐛 Bug Fixes
Fix swizzling subclass of already swizzled class (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1284)
Always remove the window when an InApp Message is dismissed ([Always remove the window when an IAM is dismissed  #1276](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1284))
🧰 Improvements
Make web views inspectable (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1286) https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1292
Other Notes
This is the first 3.X.X version built using Xcode 14.1 build. This requires that we remove the armv7s architecture from supported architectures. It also requires that our minimum deployment target is bumped to iOS 11.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Updating package.swift for release 3.12.6

- Package.swift
In this major version release for the OneSignal iOS SDK, we are making a significant shift from a device-centered model to a user-centered model. A user-centered model allows for more powerful omni-channel integrations within the OneSignal platform.
Push Subscription Update Fixes [#1289 
](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1289)Session Influence Updates [#1288 ](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1288)
Handle errors for Creating a User [#1290 ](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1290)
Fix displaying multiple In App Messages for the same trigger …
> Update package.swift for release 5.0.0

- Package.swift
In this major version release for the OneSignal iOS SDK, we are making a significant shift from a device-centered model to a user-centered model. A user-centered model allows for more powerful omni-channel integrations within the OneSignal platform.
[Fix] Remove embed bitcode flag [#1316](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1316)
Fix bug when setting app_id from cache [#1317](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1317)
Full Changelog: https://github.com/OneSignal/OneSignal-iOS-SDK/compare/5.0.1...5.0.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Release 5.0.2

- Package.swift
Note: validated the 9 zips checksums in Package.swift 
* Fix badge clearing when calling clearAll in https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1335
* Fix crash with direct influence but nil direct id https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1327
* Fix forwarding notification opens from non onesignal notifs https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1326
**Full Changelog**: https://github.com/OneSignal/OneSignal-iOS-SDK/compare/5.0.2...5.0.3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/73)
> Release 5.0.3

- Package.swift
Note: validated the 9 zips checksums in Package.swift 
* Fix badge clearing when calling clearAll in https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1335
* Fix crash with direct influence but nil direct id https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1327
* Fix forwarding notification opens from non onesignal notifs https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1326
**Full Changelog**: https://github.com/OneSignal/OneSignal-iOS-SDK/compare/5.0.2...5.0.4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/74)
> Release 5.0.4

- Package.swift
**✨ New Features**
- Add privacy manifests for the SDK (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1334)
- Add public `getTags` method (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1338)
- Fix legacy player ID was not cached properly when upgrading from v3, for sending to notification opens and confirmed deliveries (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1345)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/75)
> Release 5.0.5

- Package.swift
**✨ New Methods**
* Add getter for `onesignalId` and `externalId` and a `OSUserStateObserver` to be notified of changes in [#1344](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1344)
* See the [User Namespace API Reference](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/main/MIGRATION_GUIDE.md#user-namespace) in the Migration Guide for usage
**⚠️ Behavior Changes**
* Location sharing with OneSignal now defaults to `false` in [#1352](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1352)
* You will need to _**explicitly enable location sharing**_ with OneSignal with `OneSignal.Location.isShared = true` (in Swift) or `[OneSignal.Location setShared:true]` (in Obj-C)
**🐛 Bug Fixes & Misc Improvements**
* For our server: Add refresh_device_metadata to create user so country / IP …
> Release 5.1.0

- Package.swift
**⚠️ Behavior Changes**
* When you call the `jsonRepresentation` method of `OSPushSubscriptionState`, if a property is null, the value will now be `""` instead of the string literal `"nil"` [#1373](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1373)
**🐛 Bug Fixes & Misc Improvements**
* Rename internal method that was called `setSharedInstance` to workaround false App Store flagging [#1375](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1375)
* Improve Swift concurrency safety to address crash reports in production [#1376](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1376)
* For our server: Add `OneSignal-Subscription-Id` to Create User request which improves `last_active` data [#1372
](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1372)
- - -
This change is [<img …
> Release 5.1.1

- Package.swift
**⚠️ Behavior Changes**
* When you call the `jsonRepresentation` method of `OSPushSubscriptionState`, if a property is null, the value will now be `""` instead of the string literal `"nil"` [#1373](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1373)
**🐛 Bug Fixes & Misc Improvements**
* Rename internal method that was called `setSharedInstance` to workaround false App Store flagging [#1375](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1375)
* Improve Swift concurrency safety to address crash reports in production [#1376](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1376)
* For our server: Add `OneSignal-Subscription-Id` to Create User request which improves `last_active` data [#1372
](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1372)
- - -
This change is [<img …
> Release 5.1.3

- Package.swift
**🎉 New Features**
- Added privacy manifests in https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1360
- This release is also signed by the OneSignal certificate
------
Note: Looks like 3.12.7 was never released on OneSignal-XCFramework
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/80)
> Release 3.12.8

- Package.swift
🎉 Push to Start Live Activities
--------
To use Push To Start Live Activities, see documentation on [How to start a Live Activity with a remote push notification](https://documentation.onesignal.com/docs/push-to-start-live-activities).
In addition, new function `OneSignal.LiveActivities.setup` has been created which allows OneSignal to manage the lifecycle of a LiveActivity on behalf of the application.  This includes listening for both pushToStart token updates and pushToUpdate token updates.  When using this method, the application does not need to listen for pushToStart token updates, the starting of a live activity, nor update token updates.
---- 
SPM successfully tested.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Release 5.2.0-beta-01

- Package.swift
* The zips were previously generated before the xcframeworks were signed.
* These are generated after the xcframeworks are signed
Only affects SPM
Tested cocoapods still works with release 5.1.6
Tested SPM still works with release 5.1.6 after these changes, and unzipping shows the code signatures
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1422
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/87)
> Update Release 5.1.6 with new xcframework zips

- Package.swift
To use Push To Start Live Activities, see documentation on [How to start a Live Activity with a remote push notification](https://documentation.onesignal.com/docs/push-to-start-live-activities).
In addition, new function OneSignal.LiveActivities.setup has been created which allows OneSignal to manage the lifecycle of a LiveActivity on behalf of the application. This includes listening for both pushToStart token updates and pushToUpdate token updates. When using this method, the application does not need to listen for pushToStart token updates, the starting of a live activity, nor update token updates.
The concept of a "Default" Live Activity has also been established in the SDK, which eliminates the need for a customer app to define and manage their own ActivityAttributes.
- Push to start …
> Release 5.2.0

- Package.swift
- Fix warning about decoding a boolean (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1436)
- Fix a purchases bug for the amount spent (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1444)
- Fix a build issue for mac catalyst (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1446)
- Fix crash when IAM window fails to load by using the main thread (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1447)
- Network call optimizations: Combine user property updates for network call improvements (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1444)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/93)
> Release 5.2.1

- Package.swift
- Prevent In-App Message request crashes by making null values safe https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1457
- Add Dispatch Queues to all executors to prevent concurrency crashes https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1454
- Fix clearing notifications incorrectly such as when pulling down the notification center https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1451
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/94)
> Release 5.2.2

- Package.swift
- The user executor needs to uncache first which fixes some cached requests being dropped for past users https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1465
- Omit misleading fatal-level log for cross-platform SDKs https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1468
- [For our server] Use only OneSignal ID for requests https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1464
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/96)
> Release 5.2.3

- Package.swift
- [Fix] Handle incorrect `404` by delaying making updates to new users or subscriptions ([#1470](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1470))
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/97)
> Release 5.2.4

- Package.swift
- Pausing IAMs dismisses any currently showing IAM ([#1480](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1480))
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/98)
> Release 5.2.5

- Package.swift
- Improve segment membership calculation that allows for fetching more accurate and updated in-app messages for a user in https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1486
- Don't use cached in-app messages if the SDK encounters an error fetching them or when the server returns none in https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1499
- https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1500
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/103)
> Release 5.2.6

- Package.swift
- Fix [__NSPlaceholderDictionary initWithObjects:forKeys:count:] crashes caused by nil HTTPResponse headers (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1518)
- Include debug symbols (dSYM) in the SDK (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1519)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/107)
> Release 5.2.8

- Package.swift
- [Fix] Use new OneSignalClientError type for callbacks which fixes crash report of `NSInvalidArgumentException` [#1528](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1528)
- [Fix] Don't evaluate in app messages when paused which fixes issues with duration-since-last In-App Messages when pausing and unpausing [#1524](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1524)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OneSignal/OneSignal-XCFramework/109)
> Release 5.2.9
